"""
NAWI TestFlow — AI Assistance Service

Optional AI-powered assistance for explaining results, summarizing reports,
and extracting document metadata.

CRITICAL DESIGN PRINCIPLE:
    This module is ASSISTANCE ONLY. It never determines compliance,
    never calculates official values, and never overrides the
    deterministic calculation/compliance engine.

ARCHITECTURE:
    The deterministic engine (calculation_engine, compliance_engine)
    remains the SOLE source of truth for:
    - Official calculation results
    - PASS/FAIL determinations
    - Compliance decisions
    - Regulatory rule application

    This AI module provides:
    - Natural language explanations of existing results
    - Summaries of report content
    - Explanations of validation warnings
    - Document metadata extraction (OCR-like)
    - Human-readable test summaries

INVARIANTS:
    1. Every AI output includes a clear disclaimer
    2. AI cannot modify, override, or influence calculations
    3. AI cannot modify, override, or influence compliance decisions
    4. AI cannot invent OIML requirements or limits
    5. If AI is unavailable, the entire application continues to function
    6. AI output is always labeled as "AI-Generated Assistance"
    7. AI output is never stored as authoritative data
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Any

try:
    from google import genai
except Exception:  # pragma: no cover - optional dependency guard
    genai = None  # type: ignore

from . import rule_explainer
from .ai_settings import get_ai_settings


# ============================================================================
# ENUMERATIONS
# ============================================================================

class AIAssistanceType(str, Enum):
    """Types of AI assistance available."""
    EXPLAIN_RESULT = "explain_result"
    SUMMARIZE_REPORT = "summarize_report"
    EXPLAIN_VALIDATION = "explain_validation"
    EXTRACT_METADATA = "extract_metadata"
    GENERATE_SUMMARY = "generate_summary"


class AIConfidenceLevel(str, Enum):
    """Confidence level for AI-generated content."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# ============================================================================
# DATA TYPES
# ============================================================================

@dataclass
class AIAssistanceResponse:
    """
    Response from AI assistance service.

    Every response includes:
    - Clear labeling as AI-generated assistance
    - Confidence level
    - Disclaimer text
    - Source references (what data was used)
    - Generation timestamp
    """
    # Required fields first (no defaults)
    assistance_type: AIAssistanceType
    title: str  # Human-readable title
    content: str  # The AI-generated text

    # Optional fields with defaults
    generated_at: datetime = field(default_factory=datetime.utcnow)
    summary: Optional[str] = None  # Brief summary
    confidence: AIConfidenceLevel = AIConfidenceLevel.MEDIUM
    sources: list[str] = field(default_factory=list)  # What data was referenced
    warnings: list[str] = field(default_factory=list)  # Any caveats

    # Disclaimer (always present)
    disclaimer: str = (
        "DISCLAIMER: This content was generated by AI assistance and is "
        "provided for informational purposes only. It is NOT an official "
        "compliance determination, regulatory approval, or certification. "
        "The authoritative source for all compliance decisions is the "
        "deterministic calculation engine (OIML R-76 rules)."
    )
    # Where the content actually came from: "gemini" (live LLM call),
    # "rule-template" (deterministic template, zero AI cost), or
    # "rule-based" (pure rule_explainer output, zero AI cost).
    source: str = "rule-template"

    def to_dict(self) -> dict:
        return {
            "assistance_type": self.assistance_type.value,
            "generated_at": self.generated_at.isoformat(),
            "title": self.title,
            "content": self.content,
            "summary": self.summary,
            "confidence": self.confidence.value,
            "sources": self.sources,
            "warnings": self.warnings,
            "disclaimer": self.disclaimer,
            "source": self.source,
            "ai_used": self.source == "gemini",
        }


@dataclass
class ExtractedMetadata:
    """
    Metadata extracted from a document.

    This is AI-assisted extraction and should be verified by a human.
    The extracted values are suggestions, not authoritative data.
    """
    # Extraction results
    manufacturer: Optional[str] = None
    model: Optional[str] = None
    serial_number: Optional[str] = None
    instrument_type: Optional[str] = None
    max_capacity: Optional[float] = None
    max_capacity_unit: Optional[str] = None
    min_capacity: Optional[float] = None
    min_capacity_unit: Optional[str] = None
    scale_interval: Optional[float] = None
    scale_interval_unit: Optional[str] = None
    calibration_date: Optional[str] = None
    calibration_valid_until: Optional[str] = None
    certificate_number: Optional[str] = None

    # Raw extracted text (for verification)
    raw_text: Optional[str] = None

    # Confidence
    overall_confidence: AIConfidenceLevel = AIConfidenceLevel.MEDIUM
    field_confidence: dict[str, float] = field(default_factory=dict)

    # Disclaimer
    disclaimer: str = (
        "DISCLAIMER: This metadata was extracted by AI assistance and "
        "may contain errors. All extracted values MUST be verified by "
        "qualified laboratory personnel before use. The AI extraction "
        "is a convenience tool, not an authoritative data source."
    )

    def to_dict(self) -> dict:
        return {
            "manufacturer": self.manufacturer,
            "model": self.model,
            "serial_number": self.serial_number,
            "instrument_type": self.instrument_type,
            "max_capacity": self.max_capacity,
            "max_capacity_unit": self.max_capacity_unit,
            "min_capacity": self.min_capacity,
            "min_capacity_unit": self.min_capacity_unit,
            "scale_interval": self.scale_interval,
            "scale_interval_unit": self.scale_interval_unit,
            "calibration_date": self.calibration_date,
            "calibration_valid_until": self.calibration_valid_until,
            "certificate_number": self.certificate_number,
            "raw_text": self.raw_text,
            "overall_confidence": self.overall_confidence.value,
            "field_confidence": self.field_confidence,
            "disclaimer": self.disclaimer,
        }


# ============================================================================
# AI ASSISTANCE SERVICE
# ============================================================================

class AIAssistanceService:
    """
    Optional AI assistance service.

    This service provides natural language explanations and summaries.
    It is COMPLETELY ISOLATED from the calculation/compliance engine.

    If this service is unavailable (AI not configured, network error, etc.),
    the entire application continues to function normally.

    Usage:
        service = AIAssistanceService()
        response = service.explain_compliance_result(compliance_decision)
        # Response includes disclaimer and is labeled as AI-generated
    """

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None,
                 enabled: Optional[bool] = None):
        """
        Initialize AI assistance service.

        Args:
            api_key: Google Gemini API key (optional). If None, falls back to
                the globally configured key (admin Settings / env).
            model: Gemini model identifier (optional, defaults to settings).
            enabled: Feature flag override. If None, uses global settings.

        USAGE POLICY (cost reduction):
            Rule-based explanations (engine/rule_explainer.py) are ALWAYS
            available and must be shown first. Gemini is called ONLY on
            explicit user request AND only when a key is configured AND the
            feature is enabled. If unavailable, all methods return graceful
            deterministic fallbacks — the app never breaks without AI.
        """
        settings = get_ai_settings()
        resolved_model = model or settings.model or "gemini-2.0-flash"
        resolved_enabled = settings.enabled if enabled is None else bool(enabled)
        resolved_key = api_key or settings.resolve_key()
        self.api_key = resolved_key
        self.model = resolved_model
        self.enabled = resolved_enabled
        self._available = bool(resolved_enabled and resolved_key)
        self._http_timeout = 25.0
        if resolved_key and genai is not None:
            try:
                self._client = genai.Client(api_key=resolved_key)
            except Exception:
                self._client = None
                self._available = False
        else:
            self._client = None
            if not resolved_key:
                self._available = False

    @property
    def is_available(self) -> bool:
        """Check if Gemini may be used (enabled AND an API key is configured)."""
        # Re-check global settings so an admin toggle takes effect live.
        try:
            settings = get_ai_settings()
            if not settings.enabled or not self.enabled:
                return False
        except Exception:
            pass
        return self._available

    def _should_skip_live_call(self) -> bool:
        """Never hit the network for placeholder/test keys (keeps tests free)."""
        if not self.api_key:
            return True
        key = self.api_key.strip().lower()
        return key.startswith("test-") or key in ("test-key-123", "dummy", "changeme")

    def _rule_grounding_block(self, decision_data: Optional[dict] = None,
                              extra: Optional[str] = None) -> str:
        """Render the AUTHORITATIVE rule context Gemini must stay grounded in."""
        lines = [
            "AUTHORITATIVE RULE CONTEXT (do NOT invent or change any of this):",
        ]
        if decision_data:
            # Ground in the actual resolved rule + deterministic reason.
            rule = rule_explainer.explain_decision(decision_data) if decision_data else None
            if rule:
                lines.append(f"- Test: {rule.get('test_name')} ({rule.get('test_code')})")
                lines.append(f"- Verdict (final, immutable): {rule.get('decision')}")
                lines.append(f"- Formula actually executed: {rule.get('formula')}")
                lines.append(f"- Decision rule: {rule.get('decision_rule')}")
                lines.append(
                    f"- Observed: {rule.get('calculated_value')} {rule.get('calculated_unit')} | "
                    f"Allowed: {rule.get('applicable_limit')} {rule.get('limit_unit')} | "
                    f"Margin: {rule.get('margin')} | Excess: {rule.get('excess')}"
                )
                r = rule.get("rule", {})
                lines.append(
                    f"- Rule: {r.get('rule_id')} v{r.get('rule_version')} "
                    f"({r.get('standard')} {r.get('standard_version')})"
                )
                lines.append(f"- Official reason: {rule.get('official_reason')}")
        if extra:
            lines.append(extra)
        lines.append(
            "STRICT RULES: Rephrase/explain ONLY the above. Never invent limits, "
            "never change the verdict, never cite OIML clauses beyond what is given."
        )
        return "\n".join(lines)

    def _call_gemini(self, system_prompt: str, user_prompt: str) -> Optional[str]:
        """
        Call Google Gemini via the official google.genai SDK.

        Uses the Interactions API, which remains stable across model upgrades.
        Returns the generated text, or None if the call fails for any reason
        (no key, network error, model unavailable, empty response). Callers fall
        back to templates when this returns None, so the app never breaks
        without AI.
        """
        if not self.api_key or self._client is None:
            return None
        if self._should_skip_live_call():
            return None
        try:
            prompt = user_prompt
            if system_prompt:
                prompt = f"{system_prompt}\n\n{user_prompt}"
            interaction = self._client.interactions.create(
                model=self.model,
                input=prompt,
            )
            text = getattr(interaction, "output_text", None)
            text = text.strip() if isinstance(text, str) else ""
            return text if text else None
        except Exception:
            return None

    # ====================================================================
    # EXPLAIN RESULT
    # ====================================================================

    def explain_compliance_result(
        self,
        decision_data: dict,
    ) -> AIAssistanceResponse:
        """
        Explain a compliance decision in natural language.

        Args:
            decision_data: Serialized ComplianceDecision dict
                Must contain: test_name, decision, reason, calculated_value,
                applicable_limit, explanations

        Returns:
            AIAssistanceResponse with explanation

        IMPORTANT: This does NOT change or override the decision.
        It only provides a human-readable explanation.
        """
        if not self._available:
            return self._fallback_response(
                AIAssistanceType.EXPLAIN_RESULT,
                "AI assistance is not available. Please refer to the "
                "deterministic compliance engine results for authoritative data."
            )

        test_name = decision_data.get("test_name", "Unknown test")
        decision = decision_data.get("decision", "unknown")
        reason = decision_data.get("reason", "No reason provided")
        calculated = decision_data.get("calculated_value")
        limit = decision_data.get("applicable_limit")
        explanations = decision_data.get("explanations", [])

        # Try live Gemini first (grounded in the ACTUAL rule); fall back to
        # deterministic templates (zero AI cost).
        grounding = self._rule_grounding_block(decision_data)
        content = self._call_gemini(
            system_prompt=(
                "You are a metrology assistant helping explain an OIML R-76 "
                "compliance decision. Be clear, factual and concise. The decision, "
                "values and limits below are AUTHORITATIVE from the deterministic "
                "engine — rephrase them in plain language but NEVER invent, round "
                "away precision, change the verdict, or cite other clauses."
                f"\n\n{grounding}"
            ),
            user_prompt=(
                f"Explain the following compliance test result:\n"
                f"- Test: {test_name}\n"
                f"- Decision: {decision}\n"
                f"- Reason: {reason}\n"
                f"- Calculated value: {calculated}\n"
                f"- Applicable limit: {limit}\n"
                f"- Detailed explanations: {explanations}"
            ),
        )
        if content is None:
            content = self._generate_explanation_text(
                test_name=test_name,
                decision=decision,
                reason=reason,
                calculated_value=calculated,
                limit=limit,
                explanations=explanations,
            )
            source = "rule-template"
        else:
            source = "gemini"

        return AIAssistanceResponse(
            assistance_type=AIAssistanceType.EXPLAIN_RESULT,
            title=f"Explanation: {test_name} — {decision.upper()}",
            content=content,
            summary=f"The {test_name.lower()} test result is {decision}. "
                    f"See detailed explanation for reasoning.",
            confidence=AIConfidenceLevel.HIGH,
            sources=[
                "Compliance engine decision data",
                "Calculation results",
                f"Rule: {decision_data.get('rule_id', 'N/A')}",
            ],
            source=source,
        )

    def _generate_explanation_text(
        self,
        test_name: str,
        decision: str,
        reason: str,
        calculated_value: Optional[float],
        limit: Optional[float],
        explanations: list[dict],
    ) -> str:
        """Generate natural language explanation from structured data."""
        lines = [
            f"## Explanation: {test_name} Test",
            "",
            f"**Decision:** {decision.upper()}",
            "",
            "**What was measured:**",
            f"The {test_name.lower()} test evaluates the instrument's performance "
            f"against OIML R-76 requirements.",
            "",
        ]

        if calculated_value is not None and limit is not None:
            margin = limit - calculated_value
            lines.extend([
                "**Key values:**",
                f"- Measured value: {calculated_value}",
                f"- Maximum allowed: {limit}",
                f"- Margin: {margin}",
                "",
            ])

        if explanations:
            lines.append("**Detailed comparison:**")
            for expl in explanations:
                param = expl.get("parameter_name", "Unknown")
                obs = expl.get("observed_value", "N/A")
                allowed = expl.get("allowed_value", "N/A")
                within = expl.get("is_within_limit", False)
                status = "✓ Within limit" if within else "✗ Exceeds limit"
                lines.append(f"- {param}: {obs} vs {allowed} → {status}")
            lines.append("")

        lines.extend([
            "**Official determination:**",
            f"{reason}",
            "",
            "---",
            "*This explanation was generated by AI assistance for informational "
            "purposes. The authoritative compliance determination was made by "
            "the deterministic calculation engine. AI assistance does not "
            "override, modify, or influence compliance decisions.*",
        ])

        return "\n".join(lines)

    # ====================================================================
    # SUMMARIZE REPORT
    # ====================================================================

    def summarize_report(
        self,
        report_data: dict,
    ) -> AIAssistanceResponse:
        """
        Generate a summary of a test report.

        Args:
            report_data: Serialized test report data

        Returns:
            AIAssistanceResponse with summary

        This generates a natural-language summary for quick understanding.
        It does NOT create, modify, or override the official report.
        """
        if not self._available:
            return self._fallback_response(
                AIAssistanceType.SUMMARIZE_REPORT,
                "AI assistance is not available. Please view the full "
                "report for details."
            )

        report_number = report_data.get("report_number", "Unknown")
        test_results = report_data.get("test_results", [])
        instrument = report_data.get("instrument", {})
        overall_result = report_data.get("overall_result", "unknown")

        # Count results
        pass_count = sum(1 for r in test_results if r.get("decision") == "pass")
        fail_count = sum(1 for r in test_results if r.get("decision") == "fail")
        total = len(test_results)

        # Try live Gemini first (grounded in actual report data); fall back to
        # deterministic templating (zero AI cost).
        grounding = self._rule_grounding_block(
            None,
            extra=(
                f"Report {report_number}: overall={overall_result}, "
                f"passed {pass_count}/{total}. Instrument={instrument}. "
                f"Per-test: {test_results}. Only summarize what is listed."
            ),
        )
        content = self._call_gemini(
            system_prompt=(
                "You are a metrology assistant summarizing an OIML R-76 test "
                "report. Be concise, factual and clear. Do not invent data; "
                "only summarize what is provided. Never change any verdict."
                f"\n\n{grounding}"
            ),
            user_prompt=(
                f"Summarize this test report:\n"
                f"- Report number: {report_number}\n"
                f"- Overall result: {overall_result}\n"
                f"- Instrument: {instrument}\n"
                f"- Tests passed: {pass_count}/{total}\n"
                f"- Test results: {test_results}"
            ),
        )
        if content is None:
            lines = [
                f"## Report Summary: {report_number}",
                "",
                f"**Overall Result:** {overall_result.upper()}",
                "",
                "**Instrument:**",
                f"- Manufacturer: {instrument.get('manufacturer', 'N/A')}",
                f"- Model: {instrument.get('model', 'N/A')}",
                f"- Serial: {instrument.get('serial_number', 'N/A')}",
                "",
                f"**Test Results:** {pass_count}/{total} passed",
                "",
            ]

            if test_results:
                lines.append("**Individual test outcomes:**")
                for result in test_results:
                    name = result.get("test_name", "Unknown")
                    status = result.get("decision", "unknown")
                    marker = "✓" if status == "pass" else "✗" if status == "fail" else "—"
                    lines.append(f"- {marker} {name}: {status.upper()}")
                lines.append("")

            lines.extend([
                "---",
                "*This summary was generated by AI assistance for quick reference. "
                "Please refer to the full official report for complete details.*",
            ])

            content = "\n".join(lines)
            source = "rule-template"
        else:
            source = "gemini"

        return AIAssistanceResponse(
            assistance_type=AIAssistanceType.SUMMARIZE_REPORT,
            title=f"Summary: {report_number}",
            content=content,
            summary=f"Report {report_number}: {overall_result.upper()} — "
                    f"{pass_count}/{total} tests passed.",
            confidence=AIConfidenceLevel.HIGH,
            sources=[
                "Official test report data",
                "Compliance engine results",
            ],
            source=source,
        )

    # ====================================================================
    # EXPLAIN VALIDATION WARNING
    # ====================================================================

    def explain_validation_warning(
        self,
        warning_data: dict,
        context: Optional[dict] = None,
    ) -> AIAssistanceResponse:
        """
        Explain a validation warning in plain language.

        Args:
            warning_data: Serialized validation error/warning
            context: Additional context about the test

        Returns:
            AIAssistanceResponse with explanation

        This helps laboratory staff understand why a warning was raised
        and what action, if any, should be taken.
        """
        if not self._available:
            return self._fallback_response(
                AIAssistanceType.EXPLAIN_VALIDATION,
                "AI assistance is not available. Please refer to the "
                "validation error codes and field descriptions."
            )

        field_name = warning_data.get("field", "unknown field")
        message = warning_data.get("message", "No message")
        code = warning_data.get("code", "UNKNOWN")
        severity = warning_data.get("severity", "warning")
        value = warning_data.get("value")

        # Try live Gemini first (grounded in the actual warning); fall back to
        # deterministic templating (zero AI cost).
        content = self._call_gemini(
            system_prompt=(
                "You are a metrology assistant explaining data validation "
                "warnings. Be helpful, factual and concise. Explain ONLY the "
                "warning given below in plain language with a suggested action. "
                "Do not invent validation rules or cite other clauses."
            ),
            user_prompt=(
                f"Explain this validation warning:\n"
                f"- Field: {field_name}\n"
                f"- Code: {code}\n"
                f"- Severity: {severity}\n"
                f"- Value: {value}\n"
                f"- Message: {message}\n"
                "Include what it means and a suggested action."
            ),
        )

        if content is None:
            lines = [
                f"## Validation Warning: {field_name}",
                "",
                f"**Code:** {code}",
                f"**Severity:** {severity.upper()}",
                "",
                "**What this means:**",
                self._interpret_warning(code, field_name, value),
                "",
                "**Suggested action:**",
                self._suggest_action(code, field_name),
                "",
                "---",
                "*This explanation was generated by AI assistance. The validation "
                "warning itself was raised by the deterministic data validation "
                "engine. AI assistance does not modify validation rules.*",
            ]
            content = "\n".join(lines)
            source = "rule-template"
        else:
            source = "gemini"

        return AIAssistanceResponse(
            assistance_type=AIAssistanceType.EXPLAIN_VALIDATION,
            title=f"Warning Explanation: {field_name}",
            content=content,
            summary=f"Validation warning on '{field_name}': {message}",
            confidence=AIConfidenceLevel.MEDIUM,
            sources=[
                "Validation engine",
                f"Field: {field_name}",
                f"Code: {code}",
            ],
            source=source,
        )

    def _interpret_warning(self, code: str, field_name: str, value: Any) -> str:
        """Interpret a validation warning code into plain language."""
        interpretations = {
            "DUPLICATE_SERIAL": (
                f"The serial number '{value}' already exists in the system. "
                "This may indicate a duplicate instrument record. Verify that "
                "this is a different physical instrument before proceeding."
            ),
            "OUT_OF_RANGE": (
                f"The value '{value}' for field '{field_name}' is outside "
                "the expected range. This may indicate a data entry error. "
                "Please verify the value against the instrument documentation."
            ),
            "MISSING_REQUIRED": (
                f"Required field '{field_name}' is missing or empty. "
                "This field must be completed before the test can proceed."
            ),
            "CALIBRATION_EXPIRING": (
                f"The calibration for this equipment is approaching expiry. "
                "Consider scheduling re-calibration before the next test cycle."
            ),
        }

        return interpretations.get(
            code,
            f"Validation warning on field '{field_name}' (code: {code}). "
            "Please review the field value and correct any errors."
        )

    def _suggest_action(self, code: str, field_name: str) -> str:
        """Suggest action for a validation warning."""
        actions = {
            "DUPLICATE_SERIAL": (
                "1. Check if this instrument is already registered\n"
                "2. If different instrument, use a unique serial number\n"
                "3. If same instrument, update the existing record"
            ),
            "OUT_OF_RANGE": (
                "1. Verify the value against the instrument nameplate\n"
                "2. Check the unit of measurement\n"
                "3. Re-enter the value if incorrect"
            ),
            "MISSING_REQUIRED": (
                "1. Locate the required information\n"
                "2. Enter the value from official documentation\n"
                "3. If unavailable, contact the laboratory manager"
            ),
            "CALIBRATION_EXPIRING": (
                "1. Schedule re-calibration with an accredited lab\n"
                "2. Do not use this equipment for official testing\n"
                "3. Update calibration records after re-calibration"
            ),
        }

        return actions.get(
            code,
            "Review the validation warning and take appropriate action."
        )

    # ====================================================================
    # EXTRACT METADATA FROM DOCUMENT
    # ====================================================================

    def extract_metadata_from_document(
        self,
        document_text: str,
        document_type: str = "unknown",
    ) -> ExtractedMetadata:
        """
        Extract instrument metadata from a document.

        Args:
            document_text: Text content of the document
            document_type: Type of document (certificate, manual, etc.)

        Returns:
            ExtractedMetadata with suggestions

        IMPORTANT: All extracted values are SUGGESTIONS ONLY.
        They MUST be verified by qualified personnel before use.
        """
        if not self._available:
            return ExtractedMetadata(
                overall_confidence=AIConfidenceLevel.LOW,
                field_confidence={},
                raw_text=document_text[:1000] if document_text else None,
            )

        # Extract patterns (simplified for demonstration)
        # In production, this would call an actual AI/OCR service
        metadata = ExtractedMetadata(
            raw_text=document_text[:2000] if document_text else None,
            overall_confidence=AIConfidenceLevel.MEDIUM,
        )

        # Pattern-based extraction (simplified)
        if document_text:
            text_lower = document_text.lower()

            # Manufacturer patterns
            manufacturers = [
                "mettler toledo", "sartorius", "avery", "essae",
                "shinko", "a&d", "radwag", "kern", "ohaus",
            ]
            for mfr in manufacturers:
                if mfr in text_lower:
                    metadata.manufacturer = mfr.title()
                    metadata.field_confidence["manufacturer"] = 0.7
                    break

            # Serial number patterns
            import re
            serial_patterns = [
                r"serial\s*(?:no|number|#)?[:\s]*([A-Z0-9\-]+)",
                r"s/?n[:\s]*([A-Z0-9\-]+)",
                r"ser[:\s]*([A-Z0-9\-]+)",
            ]
            for pattern in serial_patterns:
                match = re.search(pattern, document_text, re.IGNORECASE)
                if match:
                    metadata.serial_number = match.group(1)
                    metadata.field_confidence["serial_number"] = 0.6
                    break

            # Capacity patterns
            capacity_pattern = r"(?:max(?:imum)?\s*(?:capacity|load)?)[:\s]*(\d+\.?\d*)\s*(mg|g|kg|t)"
            match = re.search(capacity_pattern, text_lower)
            if match:
                metadata.max_capacity = float(match.group(1))
                metadata.max_capacity_unit = match.group(2)
                metadata.field_confidence["max_capacity"] = 0.5

        return metadata

    # ====================================================================
    # GENERATE TEST SUMMARY
    # ====================================================================

    def generate_test_summary(
        self,
        test_data: dict,
    ) -> AIAssistanceResponse:
        """
        Generate a human-readable test summary.

        Args:
            test_data: Serialized test data including observations,
                       calculations, and results

        Returns:
            AIAssistanceResponse with summary

        This creates a narrative summary suitable for report remarks.
        It does NOT replace official test documentation.
        """
        if not self._available:
            return self._fallback_response(
                AIAssistanceType.GENERATE_SUMMARY,
                "AI assistance is not available. Please write the test "
                "summary manually."
            )

        test_name = test_data.get("test_name", "Unknown test")
        observations = test_data.get("observations", [])
        calculations = test_data.get("calculations", {})
        result = test_data.get("result", "unknown")

        # Try live Gemini first (grounded in actual observations); fall back to
        # deterministic templating (zero AI cost).
        grounding = self._rule_grounding_block(
            None,
            extra=(
                f"Test={test_name}, result={result}, observations={observations}, "
                f"calculations={calculations}. Mention only these values."
            ),
        )
        content = self._call_gemini(
            system_prompt=(
                "You are a metrology assistant writing a human-readable test "
                "summary for an OIML R-76 report. Be factual and concise. "
                "Rephrase ONLY the observations/calculations given. Do not invent "
                "values, limits or verdicts."
                f"\n\n{grounding}"
            ),
            user_prompt=(
                f"Write a test summary:\n"
                f"- Test name: {test_name}\n"
                f"- Result: {result}\n"
                f"- Observations: {observations}\n"
                f"- Calculations: {calculations}"
            ),
        )

        if content is None:
            lines = [
                f"## Test Summary: {test_name}",
                "",
                "**Procedure:**",
                f"The {test_name.lower()} test was conducted in accordance "
                f"with OIML R-76 requirements.",
                "",
            ]

            if observations:
                lines.append("**Observations:**")
                lines.append(f"- Number of test points: {len(observations)}")
                if observations:
                    first = observations[0] if isinstance(observations[0], dict) else {}
                    if first.get("unit"):
                        lines.append(f"- Unit of measurement: {first['unit']}")
                lines.append("")

            if calculations:
                lines.append("**Calculated Results:**")
                for key, value in calculations.items():
                    if isinstance(value, (int, float)):
                        lines.append(f"- {key}: {value:.4f}")
                lines.append("")

            lines.extend([
                f"**Result:** {result.upper()}",
                "",
                "---",
                "*This summary was generated by AI assistance. The official "
                "test record and calculation results are the authoritative "
                "source. This summary may be included in report remarks at "
                "the discretion of the reviewing officer.*",
            ])
            content = "\n".join(lines)
            source = "rule-template"
        else:
            source = "gemini"

        return AIAssistanceResponse(
            assistance_type=AIAssistanceType.GENERATE_SUMMARY,
            title=f"Test Summary: {test_name}",
            content=content,
            summary=f"{test_name} test completed. Result: {result.upper()}.",
            confidence=AIConfidenceLevel.MEDIUM,
            sources=[
                "Test observation data",
                "Calculation engine results",
                "OIML R-76 test procedures",
            ],
            source=source,
        )

    # ====================================================================
    # FALLBACK
    # ====================================================================

    def _fallback_response(
        self,
        assistance_type: AIAssistanceType,
        message: str,
    ) -> AIAssistanceResponse:
        """Return a graceful fallback when Gemini is unavailable/gated."""
        return AIAssistanceResponse(
            assistance_type=assistance_type,
            title="AI Assistance Unavailable",
            content=(
                message + " Tip: rule-based explanations below need no API key. "
                "To enable 'Enhance with AI', add a Gemini API key in Settings "
                "(user Settings, or admin System Settings for all users)."
            ),
            summary="AI assistance is not configured or unavailable.",
            confidence=AIConfidenceLevel.LOW,
            warnings=[
                "AI service is not available",
                "The application functions fully without AI assistance",
                "Rule-based explanations remain available at zero AI cost",
            ],
            disclaimer=(
                "DISCLAIMER: AI assistance is not available. The application "
                "continues to function normally. All compliance determinations "
                "are made by the deterministic calculation engine."
            ),
            source="rule-based",
        )


# ============================================================================
# SINGLETON
# ============================================================================

_service: Optional[AIAssistanceService] = None


def get_ai_service(api_key: Optional[str] = None) -> AIAssistanceService:
    """
    Get the AI assistance service singleton.

    Resolution order for the key: explicit api_key arg (personal user key
    from Settings) -> admin-configured global key -> GEMINI_API_KEY env.
    The global enabled flag from Settings is always respected. If no key is
    available or the feature is disabled, the service reports unavailable and
    callers fall back to deterministic rule-based explanations.
    """
    global _service
    if _service is None:
        import os
        settings = get_ai_settings()
        key = api_key or settings.resolve_key() or os.environ.get("GEMINI_API_KEY")
        model = settings.model or os.environ.get("GEMINI_MODEL")
        _service = AIAssistanceService(api_key=key, model=model,
                                       enabled=settings.enabled)
    return _service


def reset_ai_service():
    """Reset the AI service (for testing)."""
    global _service
    _service = None
