"""
NAWI TestFlow — AI Assistance API Routes

Optional AI-powered assistance endpoints.

IMPORTANT: These endpoints provide ASSISTANCE ONLY.
They do NOT determine compliance, calculate values, or override results.
Every response includes a clear disclaimer.

If AI is unavailable, endpoints return graceful fallback responses
and the application continues to function normally.
"""

from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import JSONResponse

from app.core.security import (
    require_permission,
    get_current_user_profile,
)
from app.core.exceptions import NotFoundError, ValidationError
from engine.ai_assistance import (
    AIAssistanceService,
    AIAssistanceType,
    get_ai_service,
)

router = APIRouter(prefix="/ai", tags=["ai-assistance"])


# ============================================================================
# AI DISCLAIMER HEADER
# ============================================================================

AI_DISCLAIMER = (
    "This content was generated by AI assistance. It is NOT an official "
    "compliance determination, regulatory approval, or certification. "
    "The authoritative source for all compliance decisions is the "
    "deterministic calculation engine."
)


# ============================================================================
# EXPLAIN COMPLIANCE RESULT
# ============================================================================

@router.post(
    "/explain-result",
    summary="AI: Explain compliance result",
    description=(
        "Generate a natural-language explanation of a compliance decision. "
        "ASSISTANCE ONLY — does not modify or override the decision."
    ),
)
async def explain_compliance_result(
    decision_data: dict,
    current_user: dict = Depends(require_permission("test_reports:read_completed")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    """
    Explain a compliance decision in natural language.

    This is AI assistance only. The compliance decision is authoritative.
    """
    response = ai_service.explain_compliance_result(decision_data)

    return {
        "assistance": response.to_dict(),
        "_meta": {
            "type": "ai_assistance",
            "authoritative_source": "deterministic_compliance_engine",
            "disclaimer": AI_DISCLAIMER,
            "generated_at": datetime.utcnow().isoformat(),
        },
    }


# ============================================================================
# SUMMARIZE REPORT
# ============================================================================

@router.post(
    "/summarize-report",
    summary="AI: Summarize test report",
    description=(
        "Generate a natural-language summary of a test report. "
        "ASSISTANCE ONLY — does not create or modify the official report."
    ),
)
async def summarize_report(
    report_data: dict,
    current_user: dict = Depends(require_permission("reports:read")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    """
    Generate a summary of a test report.

    This is AI assistance only. The official report is authoritative.
    """
    response = ai_service.summarize_report(report_data)

    return {
        "assistance": response.to_dict(),
        "_meta": {
            "type": "ai_assistance",
            "authoritative_source": "official_test_report",
            "disclaimer": AI_DISCLAIMER,
            "generated_at": datetime.utcnow().isoformat(),
        },
    }


# ============================================================================
# EXPLAIN VALIDATION WARNING
# ============================================================================

@router.post(
    "/explain-validation",
    summary="AI: Explain validation warning",
    description=(
        "Explain a validation warning in plain language. "
        "ASSISTANCE ONLY — does not modify validation rules."
    ),
)
async def explain_validation_warning(
    warning_data: dict,
    context: Optional[dict] = None,
    current_user: dict = Depends(require_permission("test_data:create")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    """
    Explain a validation warning in plain language.

    This helps laboratory staff understand validation issues.
    """
    response = ai_service.explain_validation_warning(
        warning_data=warning_data,
        context=context,
    )

    return {
        "assistance": response.to_dict(),
        "_meta": {
            "type": "ai_assistance",
            "authoritative_source": "validation_engine",
            "disclaimer": AI_DISCLAIMER,
            "generated_at": datetime.utcnow().isoformat(),
        },
    }


# ============================================================================
# EXTRACT METADATA FROM DOCUMENT
# ============================================================================

@router.post(
    "/extract-metadata",
    summary="AI: Extract instrument metadata",
    description=(
        "Extract instrument metadata from a document. "
        "ASSISTANCE ONLY — all extracted values must be verified by personnel."
    ),
)
async def extract_metadata(
    document_text: str,
    document_type: str = "unknown",
    current_user: dict = Depends(require_permission("instruments:create")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    """
    Extract instrument metadata from a document.

    All extracted values are SUGGESTIONS ONLY.
    They MUST be verified by qualified laboratory personnel before use.
    """
    metadata = ai_service.extract_metadata_from_document(
        document_text=document_text,
        document_type=document_type,
    )

    return {
        "extracted": metadata.to_dict(),
        "_meta": {
            "type": "ai_assistance",
            "authoritative_source": None,
            "disclaimer": (
                "All extracted values are suggestions only. "
                "They MUST be verified by qualified personnel before use."
            ),
            "generated_at": datetime.utcnow().isoformat(),
        },
    }


# ============================================================================
# GENERATE TEST SUMMARY
# ============================================================================

@router.post(
    "/generate-summary",
    summary="AI: Generate test summary",
    description=(
        "Generate a human-readable test summary. "
        "ASSISTANCE ONLY — does not replace official test documentation."
    ),
)
async def generate_test_summary(
    test_data: dict,
    current_user: dict = Depends(require_permission("test_reports:read_completed")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    """
    Generate a human-readable test summary.

    This summary may be included in report remarks at the discretion
    of the reviewing officer.
    """
    response = ai_service.generate_test_summary(test_data)

    return {
        "assistance": response.to_dict(),
        "_meta": {
            "type": "ai_assistance",
            "authoritative_source": "test_observations_and_calculations",
            "disclaimer": AI_DISCLAIMER,
            "generated_at": datetime.utcnow().isoformat(),
        },
    }


# ============================================================================
# AI SERVICE STATUS
# ============================================================================

@router.get(
    "/status",
    summary="AI: Check service status",
    description="Check if AI assistance is available.",
)
async def get_ai_status(
    current_user: dict = Depends(require_permission("reports:read")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    """Check if AI assistance is available."""
    return {
        "available": ai_service.is_available,
        "model": ai_service.model if ai_service.is_available else None,
        "message": (
            "AI assistance is available."
            if ai_service.is_available
            else "AI assistance is not configured. The application "
                 "functions normally without it."
        ),
    }
