"""
NAWI TestFlow — AI Assistance API Routes.

Two-tier explanation strategy (cost-aware):

TIER 1 — RULE-BASED (default, always available, zero AI cost):
    POST /ai/explain-rule      explain one compliance decision (why pass/fail)
    POST /ai/summarize-rule    summarize a report from authoritative data
    GET  /ai/process/{code}    how a test works (formula + procedure)
    These NEVER call Gemini and need NO api key.

TIER 2 — GEMINI ENHANCEMENT (on-demand only):
    POST /ai/explain-result, /summarize-report, /explain-validation,
         /generate-summary, /extract-metadata
    Gemini is called ONLY when the caller passes mode="ai" (or legacy
    behaviour) AND an API key is configured (personal per-request key via
    X-Gemini-Key header / api_key field, else admin global key from Settings)
    AND the feature is enabled. Otherwise a rule-based fallback is returned
    with ai_used=false + setup_required=true so the UI can prompt for a key
    instead of silently burning AI calls.

SETTINGS (gating):
    GET /ai/settings   any authenticated user — public status (key masked)
    PUT /ai/settings   admin only — enabled flag, model, global key
    DELETE /ai/settings/key  admin only — clear global key
"""

from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, Header, HTTPException, status
from pydantic import BaseModel

from app.core.security import (
    require_permission,
    require_admin,
    require_authenticated,
)
from engine.ai_assistance import (
    AIAssistanceService,
    AIAssistanceType,
    get_ai_service,
)
from engine import rule_explainer
from engine.ai_settings import get_ai_settings, update_ai_settings

router = APIRouter(prefix="/ai", tags=["ai-assistance"])


AI_DISCLAIMER = (
    "This content was generated by AI assistance. It is NOT an official "
    "compliance determination, regulatory approval, or certification. "
    "The authoritative source for all compliance decisions is the "
    "deterministic calculation engine."
)

RULE_NOTE = (
    "Rule-based explanation from the deterministic compliance engine "
    "(no AI used, no API key needed)."
)


# ============================================================================
# Helpers
# ============================================================================

def _service_for_request(
    x_gemini_key: Optional[str] = None,
    body_key: Optional[str] = None,
) -> AIAssistanceService:
    """Build a request-scoped service: personal key > global key > env."""
    personal = (body_key or "").strip() or (x_gemini_key or "").strip() or None
    settings = get_ai_settings()
    resolved = settings.resolve_key(personal)
    return AIAssistanceService(
        api_key=resolved, model=settings.model, enabled=settings.enabled
    )


def _meta(authoritative_source: str, ai_used: bool, source: str) -> dict:
    return {
        "type": "ai_assistance" if ai_used else "rule_based_explanation",
        "authoritative_source": authoritative_source,
        "ai_used": ai_used,
        "source": source,
        "disclaimer": AI_DISCLAIMER if ai_used else RULE_NOTE,
        "generated_at": datetime.utcnow().isoformat(),
    }


# ============================================================================
# TIER 1 — RULE-BASED (no key, no AI)
# ============================================================================

@router.post(
    "/explain-rule",
    summary="Rule-based: explain compliance result (no AI)",
    description=(
        "Deterministic explanation of a compliance decision: formula actually "
        "executed, observed vs allowed, margin/excess, why it passed/failed, "
        "and the exact rule + version. Always available, zero AI cost."
    ),
)
async def explain_rule(
    decision_data: dict,
    current_user: dict = Depends(require_permission("test_reports:read_completed")),
):
    explanation = rule_explainer.explain_decision(decision_data or {})
    return {"explanation": explanation, "_meta": _meta(
        "deterministic_compliance_engine", False, "rule-based")}


@router.post(
    "/summarize-rule",
    summary="Rule-based: summarize test report (no AI)",
    description=(
        "Deterministic report summary (counts, headline, per-test lines) "
        "computed from compliance decisions. Always available, zero AI cost."
    ),
)
async def summarize_rule(
    report_data: dict,
    current_user: dict = Depends(require_permission("reports:read")),
):
    summary = rule_explainer.summarize_report(report_data or {})
    return {"summary": summary, "_meta": _meta(
        "official_test_report", False, "rule-based")}


@router.get(
    "/process/{test_code}",
    summary="Rule-based: how a test works (no AI)",
    description=(
        "Process explanation for a test code (formula, decision rule, steps). "
        "Helps users understand the process without invoking AI."
    ),
)
async def explain_process(
    test_code: str,
    current_user: dict = Depends(require_authenticated),
):
    process = rule_explainer.explain_process(test_code)
    return {"process": process, "_meta": _meta(
        "configured_oiml_r76_rules", False, "rule-based")}


# ============================================================================
# SETTINGS (gating for Tier 2)
# ============================================================================

class AISettingsUpdate(BaseModel):
    enabled: Optional[bool] = None
    model: Optional[str] = None
    api_key: Optional[str] = None
    clear_key: bool = False


@router.get(
    "/settings",
    summary="AI settings status",
    description="Public AI status (key masked). Any authenticated user.",
)
async def get_settings_status(
    current_user: dict = Depends(require_authenticated),
):
    settings = get_ai_settings()
    data = settings.public_status()
    data["masked_key"] = settings.masked_key()
    return data


@router.put(
    "/settings",
    summary="Admin: update AI settings",
    description=(
        "Admin-only. Change enabled flag, Gemini model, or the global API key "
        "(applies to all users unless they supply a personal key). "
        "All other system settings remain editable on the admin Settings page."
    ),
)
async def put_settings_status(
    payload: AISettingsUpdate,
    current_user: dict = Depends(require_admin),
):
    try:
        settings = update_ai_settings(
            enabled=payload.enabled,
            model=payload.model,
            api_key=payload.api_key,
            clear_key=payload.clear_key,
        )
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))
    data = settings.public_status()
    data["masked_key"] = settings.masked_key()
    return data


@router.delete(
    "/settings/key",
    summary="Admin: clear global API key",
    description="Admin-only. Removes the global Gemini key (disables Tier 2 until re-added).",
)
async def delete_global_key(
    current_user: dict = Depends(require_admin),
):
    settings = update_ai_settings(clear_key=True)
    data = settings.public_status()
    data["masked_key"] = settings.masked_key()
    return data


# ============================================================================
# TIER 2 — GEMINI ENHANCEMENT (on-demand, gated)
# Request model: { ..., "mode": "rule" | "ai", "api_key": "<personal key>" }
# ============================================================================

def _extract_mode_and_key(payload: dict) -> tuple[str, Optional[str]]:
    mode = str(payload.pop("mode", "ai") or "ai").lower()
    key = payload.pop("api_key", None)
    if key is not None:
        key = str(key).strip() or None
    if mode not in ("rule", "ai"):
        mode = "ai"
    return mode, key


@router.post(
    "/explain-result",
    summary="Explain compliance result (rule-first, optional AI)",
    description=(
        "Default mode='rule' returns the deterministic explanation (no AI). "
        "Pass mode='ai' to explicitly request Gemini enhancement (requires key)."
    ),
)
async def explain_compliance_result(
    decision_data: dict,
    current_user: dict = Depends(require_permission("test_reports:read_completed")),
    x_gemini_key: Optional[str] = Header(default=None),
):
    mode, body_key = _extract_mode_and_key(decision_data)
    if mode == "rule":
        explanation = rule_explainer.explain_decision(decision_data)
        return {"explanation": explanation,
                "_meta": _meta("deterministic_compliance_engine", False, "rule-based")}
    svc = _service_for_request(x_gemini_key, body_key)
    if not svc.is_available:
        explanation = rule_explainer.explain_decision(decision_data)
        meta = _meta("deterministic_compliance_engine", False, "rule-based")
        meta["setup_required"] = True
        meta["hint"] = "Add a Gemini API key in Settings to enable 'Enhance with AI'."
        return {"explanation": explanation, "fallback": svc._fallback_response(
            AIAssistanceType.EXPLAIN_RESULT,
            "Gemini is not configured. Showing rule-based explanation.").to_dict(),
            "_meta": meta}
    response = svc.explain_compliance_result(decision_data)
    return {"assistance": response.to_dict(),
            "_meta": _meta("deterministic_compliance_engine",
                           response.source == "gemini", response.source)}


@router.post(
    "/summarize-report",
    summary="Summarize test report (rule-first, optional AI)",
)
async def summarize_report(
    report_data: dict,
    current_user: dict = Depends(require_permission("reports:read")),
    x_gemini_key: Optional[str] = Header(default=None),
):
    mode, body_key = _extract_mode_and_key(report_data)
    if mode == "rule":
        summary = rule_explainer.summarize_report(report_data)
        return {"summary": summary,
                "_meta": _meta("official_test_report", False, "rule-based")}
    svc = _service_for_request(x_gemini_key, body_key)
    if not svc.is_available:
        summary = rule_explainer.summarize_report(report_data)
        meta = _meta("official_test_report", False, "rule-based")
        meta["setup_required"] = True
        return {"summary": summary, "_meta": meta}
    response = svc.summarize_report(report_data)
    return {"assistance": response.to_dict(),
            "_meta": _meta("official_test_report",
                           response.source == "gemini", response.source)}


@router.post(
    "/explain-validation",
    summary="Explain validation warning (rule-first, optional AI)",
)
async def explain_validation_warning(
    payload: dict,
    current_user: dict = Depends(require_permission("test_data:create")),
    x_gemini_key: Optional[str] = Header(default=None),
):
    mode, body_key = _extract_mode_and_key(payload)
    warning_data = payload.get("warning_data", payload)
    context = payload.get("context")
    svc = _service_for_request(x_gemini_key, body_key)
    # Validation explanations are cheap deterministic templates by default.
    if mode == "rule" or not svc.is_available:
        resp = svc.explain_validation_warning(warning_data, context)
        # Force rule-template path when gated: rebuild via unavailable service
        if not svc.is_available:
            gated = AIAssistanceService(api_key=None)
            resp = gated.explain_validation_warning(warning_data, context)
            meta = _meta("validation_engine", False, "rule-based")
            meta["setup_required"] = True
            return {"assistance": resp.to_dict(), "_meta": meta}
        return {"assistance": resp.to_dict(),
                "_meta": _meta("validation_engine",
                               resp.source == "gemini", resp.source)}
    response = svc.explain_validation_warning(warning_data, context)
    return {"assistance": response.to_dict(),
            "_meta": _meta("validation_engine",
                           response.source == "gemini", response.source)}


@router.post(
    "/extract-metadata",
    summary="AI: Extract instrument metadata (gated)",
    description="Requires API key — extraction suggestions must be verified.",
)
async def extract_metadata(
    payload: dict,
    current_user: dict = Depends(require_permission("instruments:create")),
    x_gemini_key: Optional[str] = Header(default=None),
):
    document_text = payload.get("document_text", "")
    document_type = payload.get("document_type", "unknown")
    body_key = payload.get("api_key")
    svc = _service_for_request(x_gemini_key, body_key)
    if not svc.is_available:
        meta = _meta(None, False, "rule-based")  # type: ignore[arg-type]
        meta["setup_required"] = True
        meta["hint"] = "Add a Gemini API key in Settings to enable extraction."
        metadata = svc.extract_metadata_from_document(document_text, document_type)
        return {"extracted": metadata.to_dict(), "_meta": meta}
    metadata = svc.extract_metadata_from_document(document_text, document_type)
    return {
        "extracted": metadata.to_dict(),
        "_meta": {
            "type": "ai_assistance",
            "authoritative_source": None,
            "ai_used": True,
            "source": "gemini",
            "disclaimer": (
                "All extracted values are suggestions only. "
                "They MUST be verified by qualified personnel before use."
            ),
            "generated_at": datetime.utcnow().isoformat(),
        },
    }


@router.post(
    "/generate-summary",
    summary="Generate test summary (rule-first, optional AI)",
)
async def generate_test_summary(
    test_data: dict,
    current_user: dict = Depends(require_permission("test_reports:read_completed")),
    x_gemini_key: Optional[str] = Header(default=None),
):
    mode, body_key = _extract_mode_and_key(test_data)
    if mode == "rule":
        # Deterministic narrative from actual observations
        svc0 = AIAssistanceService(api_key=None)
        resp = svc0.generate_test_summary(test_data)
        return {"assistance": resp.to_dict(),
                "_meta": _meta("test_observations_and_calculations", False, "rule-template")}
    svc = _service_for_request(x_gemini_key, body_key)
    if not svc.is_available:
        svc0 = AIAssistanceService(api_key=None)
        resp = svc0.generate_test_summary(test_data)
        meta = _meta("test_observations_and_calculations", False, "rule-template")
        meta["setup_required"] = True
        return {"assistance": resp.to_dict(), "_meta": meta}
    response = svc.generate_test_summary(test_data)
    return {"assistance": response.to_dict(),
            "_meta": _meta("test_observations_and_calculations",
                           response.source == "gemini", response.source)}


@router.get(
    "/status",
    summary="AI service status (rule-based always on)",
    description="Check rule-based + Gemini availability.",
)
async def get_ai_status(
    current_user: dict = Depends(require_permission("reports:read")),
    ai_service: AIAssistanceService = Depends(get_ai_service),
):
    settings = get_ai_settings()
    pub = settings.public_status()
    return {
        "rule_based_available": True,
        "available": ai_service.is_available,
        "ai_available": ai_service.is_available,
        "ai_enabled": pub["ai_enabled"],
        "setup_required": not ai_service.is_available,
        "model": ai_service.model if ai_service.is_available else None,
        "message": (
            "AI assistance is available (on-demand only)."
            if ai_service.is_available
            else "Rule-based explanations active. Add a Gemini API key in "
                 "Settings to enable optional 'Enhance with AI'."
        ),
    }
